# Generated by Django 3.0.8 on 2020-08-12 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200807_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='GMEncounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Systolic', models.CharField(blank=True, default='0', max_length=4)),
                ('Diastolic', models.CharField(blank=True, default='0', max_length=4)),
                ('Provider_Notes', models.TextField(max_length=2000)),
                ('Medicine_List', models.TextField(default='none', max_length=500)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
            ],
        ),
    ]
