# Generated by Django 3.0.8 on 2020-08-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200812_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pain_catastrophizing_scale',
            name='q1_pcs',
            field=models.IntegerField(choices=[(-5, '-5'), (-4, '-4'), (-3, '-3'), (-2, '-2'), (-1, -1), (0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
