# Generated by Django 3.0.8 on 2020-08-19 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200817_0438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gmencounter',
            old_name='GM_Diastolic',
            new_name='Diastolic',
        ),
        migrations.RenameField(
            model_name='gmencounter',
            old_name='GM_Systolic',
            new_name='Systolic',
        ),
    ]
